<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="invpend" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass_slider" value="100" /> <!-- arbitrary value for mass -->
  <xacro:property name="mass_cart" value="0.5" /> <!-- arbitrary value for mass -->
  <xacro:property name="mass_pole" value="0.2" /> <!-- arbitrary value for mass -->
  <xacro:property name="width" value="0.25" /> <!-- cart width -->
  <xacro:property name="height" value="0.125" /> <!-- cart height -->
  <xacro:property name="depth" value="0.25" /> <!-- cart depth -->
  <xacro:property name="length_slider" value="100" /> <!-- pole length -->
  <xacro:property name="length_pole" value="0.6" /> <!-- pole length -->
  <xacro:property name="radius" value="0.01" /> <!-- slender bar radius -->
  <xacro:property name="radius_pole" value="0.025" /> <!-- pole radius -->

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find invpend_description)/urdf/invpend.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find invpend_description)/urdf/materials.xacro" />

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="slidebar"/>
    <origin xyz="0 0 1"/>
  </joint>

  <!-- Slider Link -->
  <link name="slidebar">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${length_slider} ${radius} ${radius}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass_slider}"/>
      <inertia
	  ixx="${mass_slider*length_slider*length_slider/12}" ixy="0.0" ixz="0.0"
	  iyy="0.0" iyz="0.0"
	  izz="${mass_slider*length_slider*length_slider/12}"/>
    </inertial>
  </link>

  <joint name="slider_to_cart" type="prismatic">
    <parent link="slidebar"/>
    <child link="cart"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit effort="100.0" lower="-${length_slider/2}" upper="${length_slider/2}" velocity="1000"/>
    <dynamics damping="0.1"/>
  </joint>

  <!-- Cart Link -->
  <link name="cart">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${depth} ${height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${depth} ${height}"/>	
      </geometry>
      <material name="blue"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass_cart}"/>
      <inertia
	  ixx="${mass_cart*(depth*depth+height*height)/12}" ixy="0.0" ixz="0.0"
	  iyy="${mass_cart*(depth*depth+width*width)/12}" iyz="0.0"
	  izz="${mass_cart*(width*width+height*height)/12}"/>
    </inertial>
  </link>

  <joint name="cart_to_pole" type="continuous">
    <parent link="cart"/>
    <child link="pole"/>
    <origin xyz="0 ${-depth/2-radius-radius_pole/2} ${height/4}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="1000.0" velocity="1000.0"/>
  </joint>

  <!-- Pole Link -->
  <link name="pole">
    <collision>
      <origin xyz="0 0 ${length_pole/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${radius_pole} ${radius_pole} ${length_pole}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${length_pole/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${radius_pole} ${radius_pole} ${length_pole}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${length_pole/2}" rpy="0 0 0"/>
      <mass value="${mass_pole}"/>
      <inertia
	  ixx="${mass_pole*length_pole*length_pole/3}" ixy="0.0" ixz="0.0"
	  iyy="${mass_pole*length_pole*length_pole/3}" iyz="0.0"
	  izz="${mass_pole*radius_pole*radius_pole/12}"/>
    </inertial>
  </link>

  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="slider_to_cart">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_pris">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="cart_to_pole">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor_revo">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

</robot>
